# This is a basic workflow to help you get started with Actions

name: Build & Deploy to FluxCD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Cache skaffold image builds & config
        uses: actions/cache@v2
        with:
          path: ~/.skaffold/
          key: fixed-${{ github.sha }}
          restore-keys: |
            fixed-${{ github.sha }}
            fixed-

      - name: Update Patch Verision
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git checkout -b release
          npm version patch

      - name: Build with Skaffold
        uses: hiberbee/github-action-skaffold@latest
        with:
          command: build
          repository: registry.iteam.services

      - name: Render output
        uses: hiberbee/github-action-skaffold@latest
        with:
          command: render --output deploy/latest.yaml
          cache-file: ''
          repository: registry.iteam.services

      - name: Push new manifest to FluxCD
        run: |
          git add deploy/latest.yaml
          git commit --amend --no-edit
          git push origin release --force
