version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    ports:
      - '9200:9200'
    environment:
      http.host: 0.0.0.0
      transport.host: 127.0.0.1
  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.1
    ports:
      - '5601:5601'
