# Source: pelias/templates/api-deployment.tpl
apiVersion: v1
kind: Pod
metadata:
  name: pelias-osm-importer
  namespace: pelias
spec:
  restartPolicy: Never
  initContainers:
    # NOTE:
    # This is to create the directory needed by the download as the root user
    # The download runs as non root user so it cannot create the directory
    - name: make-directory
      image: busybox
      command:
        - mkdir
        - -p
        - /data/openstreetmap
      securityContext:
        privileged: true
      volumeMounts:
        - name: data-volume
          mountPath: /data
    # NOTE:
    # This is to fix the permission on the download directory for the pelias user
    - name: fix-the-volume-permission
      image: busybox
      command:
        - sh
        - -c
        - chown -R 1000:1000 /data/openstreetmap
      securityContext:
        privileged: true
      volumeMounts:
        - name: data-volume
          mountPath: /data
    - name: download-data
      image: pelias/openstreetmap:master
      command:
        - sh
        - -c
        - ./bin/download
      env:
        - name: PELIAS_CONFIG
          value: "/etc/config/pelias.json"
      volumeMounts:
        - name: config-volume
          mountPath: /etc/config
        - name: data-volume
          mountPath: /data
  containers:
    - name: osm-importer
      image: pelias/openstreetmap:master
      command:
        - sh
        - -c
        - ./bin/start
      volumeMounts:
        - name: config-volume
          mountPath: /etc/config
        - name: data-volume
          mountPath: /data
      env:
        - name: PELIAS_CONFIG
          value: "/etc/config/pelias.json"
      resources: {}
  volumes:
    - name: config-volume
      configMap:
        name: pelias-json-configmap
        items:
          - key: pelias.json
            path: pelias.json
    - name: data-volume
      persistentVolumeClaim:
        claimName: osm-importer-pvc
---
# Source: pelias/templates/pip-pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: osm-importer-pvc
  namespace: pelias
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi